<a href="https://colab.research.google.com/github/TranNhatHan/LamBt/blob/main/BaiTapSinhNgauNhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [2]:
np.arange(-15, 27, 0.7)

array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [3]:
np.random.normal(2.7, 1.2, 40)

array([3.04463401, 3.67586701, 3.60634807, 1.81603753, 4.70849463,
       1.81276641, 1.56001041, 2.28657896, 2.44428544, 2.89148382,
       3.8024651 , 0.72132166, 1.63708702, 2.36155994, 1.27637885,
       3.13208542, 1.27524946, 1.69508704, 2.2214933 , 1.13187702,
       4.12517978, 3.23066469, 3.53089703, 4.19232096, 5.394859  ,
       1.95294351, 1.60919399, 4.33465711, 3.74222987, 4.29772687,
       1.71657336, 2.82882848, 1.96846853, 1.70705384, 2.63913619,
       3.22313381, 2.11405098, 0.77728717, 2.36383849, 3.00814538])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [4]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 17)

array(['Viet Nam', 'Viet Nam', 'Russia', 'Britain', 'Britain',
       'Singapore', 'Singapore', 'Britain', 'France', 'Russia',
       'Viet Nam', 'Viet Nam', 'Viet Nam', 'Viet Nam', 'Singapore',
       'France', 'Russia'], dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [5]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 17, p = [0.3, 0.2, 0.3, 0.1, 0.1])

array(['Viet Nam', 'Viet Nam', 'Russia', 'Viet Nam', 'France', 'Viet Nam',
       'France', 'Viet Nam', 'France', 'Viet Nam', 'France', 'Viet Nam',
       'Viet Nam', 'Britain', 'France', 'Singapore', 'France'],
      dtype='<U9')

In [6]:
import scipy.stats as st

Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [7]:
st.norm.rvs(loc = 12.7, scale = 2.6, size = 30)

array([15.78062302, 15.18161507, 15.50875957, 12.92114433, 11.15445487,
       19.49768522, 14.73835231, 12.65841116, 12.05342963,  9.87267627,
       13.34294664, 15.22034183, 10.40092857, 12.07966031,  8.79518928,
       14.42398217, 12.28316104, 13.71034275, 11.67784587,  9.17672571,
       13.20012303, 15.11148258,  9.2076288 , 13.14342581, 13.28912756,
        9.8509814 , 14.07517918, 13.54948381, 13.72631066, 10.38238766])

2. Hãy sinh một mẫu ngẫu nhiên theo phân phối Poisson

In [20]:
st.poisson.rvs(loc=-10, mu=10, size=100)

array([ 3, -2,  1, -1, -4,  3, -3,  0, -1,  3,  2, -1,  4, -3,  6, -2,  3,
        4, -1, -2, -1,  5,  3,  0,  0,  3, -4,  0, -3, -2,  3, -5,  3,  2,
        0,  3, -4,  0, -3, -3, -4, -6,  3,  3,  2,  5, -3,  3,  1,  1, -1,
       -1,  4,  9, -4,  1, -4, -3,  4, -3, -2,  5, -1,  2,  0, -7,  6,  5,
       -1, -1,  2,  4,  1,  1, -3, -2,  3,  3, -4,  3, -2,  1,  3, -3,  4,
       -5, -1, -1,  7,  0,  5,  2, -2,  8,  2,  5, -3,  4,  0,  0])