<a href="https://colab.research.google.com/github/TranNhatHan/LamBt/blob/main/BtNumPy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.array([5, 7, 4])
print(a)

In [3]:
import numpy as np
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [37]:
import numpy as np
n = int(input("Nhap n:"))
c = np.random.randn(n)
print(c)

Nhap n:3
[0.35568806 0.03797436 0.12756991]


In [31]:
import numpy as np
oa = np.array([7, -5, 8])
dist = np.linalg.norm(oa)
print(dist)

11.74734012447073


In [51]:
import numpy as np
n = int(input("Nhap n:"))
a = np.random.randn(n)
b = np.random.randn(n)
dist = np.linalg.norm(a-b)
print(dist)

Nhap n:4
3.763473440194887


In [53]:
import numpy as np
n = int(input("Nhap n:"))
a = np.random.randn(n)
b = np.random.randn(n)
c = np.inner(a,b)
print(c)

Nhap n:3
2.038046671367756


In [54]:
import numpy as np
n = int(input("Nhap n:"))
a = np.random.randn(n)
b = np.random.randn(n)
c = np.cross(a,b)
print(c)

Nhap n:3
[0.90874477 0.00236078 0.14103858]


In [58]:
import numpy as np
n = int(input("Nhap n:"))
a = np.random.randn(n)
b = np.transpose(a)
print(a)
print(b)

Nhap n:3
[ 0.5734961  -0.91941363 -1.38120338]
[ 0.5734961  -0.91941363 -1.38120338]


In [64]:
import numpy as np
a = [1, 2, 3, 4, 5]
b = [[1], [2], [3], [4], [5]]
print(a)
print(b)
va = np.array(a)
vb = np.array(b)
print(va)
print(vb)
vat = np.transpose(va)
vbt = np.transpose(vb)
print(vat)
print(vbt)

[1, 2, 3, 4, 5]
[[1], [2], [3], [4], [5]]
[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]
[[1 2 3 4 5]]


In [66]:
import numpy as np
n = int(input("Nhap n:"))
a = np.random.randn(n)
b = np.random.randn(n)
print(a*5)
print(a+b)

Nhap n:3
[ 3.31004184 -0.40086093 -2.38163134]
[ 2.18752462 -1.00702105 -0.06986343]
