<a href="https://colab.research.google.com/github/TranNhatHan/LamBt/blob/main/BtNumpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cú pháp: numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)

func1d : hàm bạn muốn thực hiện cho từng hàm hay cột

axis : số 0 nếu bạn muốn áp dụng cho từng cột, 1 nếu muốn áp dụng cho từng hàm

arr : ma trận bạn muốn áp dụng thực hiện hàm này

In [2]:
import numpy as np

Câu 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [3]:
a = np.random.randint(-20,20, (15, 17))
print(a)

[[  8  -8   8  15   4   5   7   3  13  15  16 -13  13 -14 -15  11 -17]
 [ -5 -16  19   5 -13 -11  14 -14 -18 -13   7  19  18  12  -4  18   4]
 [-19  11  -1  12  -5  -7   8   4   5  14   2 -16   7 -16 -19 -15  -6]
 [ -8 -13  13 -14   0   9  16   5   8  11 -15  11 -18   5   3  10   3]
 [  7   6  -4  12  18 -10  -1   3 -12   0  -8 -16  -2 -10   5 -14 -19]
 [-14 -18   7 -19 -20 -18   3  -7  -1   6 -17 -19  -7   1 -18  -4   4]
 [-18  -3 -17   8  -5 -15 -18   2  -2  16  10  13 -11  -9 -14  15 -20]
 [-16  -3  14   7 -13  -4  19  14  12 -19  12  -3  11  -2   0  11   9]
 [ -2  19  15   7  -3   5  17  -2   1  11 -13   0 -14  14  -1  -9 -16]
 [-13 -13   2   7   1 -15 -18 -17 -17  -7 -10   7 -17   8  18  -9   9]
 [-18   1  11  18   3  -9 -19  -7   4 -19  -4  13   2 -16  14 -10  15]
 [  0   3   8  -8  10 -11  -8   6   7  -9 -15  -6 -17   2  -9   6   2]
 [ 11  -6 -15 -14   8 -20 -11 -19 -14  18 -15  -6  -6  15  17   1 -18]
 [-14 -14 -10   8  11 -11   1 -16  17  14  15   7  10   8   5  14  18]
 [ -3 

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [4]:
def tim_gia_tri_lon_nhat(vector_a):
  return np.max(vector_a)
np.apply_along_axis(tim_gia_tri_lon_nhat, 1, a)

array([16, 19, 14, 16, 18,  7, 16, 19, 19, 18, 18, 10, 18, 18, 19])

In [5]:
np.apply_along_axis(tim_gia_tri_lon_nhat, 0, a)

array([11, 19, 19, 18, 18,  9, 19, 19, 17, 18, 16, 19, 18, 15, 18, 18, 18])

Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [6]:
def tim_gia_tri_nho_nhat(vector_a):
  return np.min(vector_a)
np.apply_along_axis(tim_gia_tri_nho_nhat, 1, a)

array([-17, -18, -19, -18, -19, -20, -20, -19, -16, -18, -19, -17, -20,
       -16, -19])

In [7]:
np.apply_along_axis(tim_gia_tri_nho_nhat, 0, a)

array([-19, -18, -17, -19, -20, -20, -19, -19, -18, -19, -18, -19, -18,
       -16, -19, -15, -20])

Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [8]:
def tinh_tong(vector_a):
  return np.sum(vector_a)
np.apply_along_axis(tinh_tong, 1, a)

array([  51,   22,  -41,   26,  -45, -141,  -68,   49,   29,  -84,  -21,
        -39,  -74,   63,  -49])

Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [9]:
def tinh_tong2(vector_a):
  sum = 0
  for i in vector_a:
    if i//2!=0:
      sum+=i
  return sum
np.apply_along_axis(tinh_tong2, 1, a)

array([  51,   22,  -41,   26,  -45, -142,  -68,   49,   28,  -85,  -22,
        -39,  -75,   62,  -49])

In [10]:
np.apply_along_axis(tinh_tong2, 0, a)

array([-104,  -50,   54,   53,    9, -122,   -2,  -26,   15,   19,  -53,
        -22,  -41,  -10,  -21,   14,  -41])