<a href="https://colab.research.google.com/github/TranNhatHan/LamBt/blob/main/BtNumPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Bài 1 - Ma trận: Trong Toán học, ma trận (matrix) là một mảng 2 chiều chứa số hoặc các đối tượng toán học khác. Một cách tổng quát ma trận A có m hàng và n cột chứa các số thực, ký hiệu là A ∈ Rm×n hay Am×n hay A = (ai,j)
m×n

In [ ]:
a = np.random.randn(7, 5)
print(a)

[[-0.94416062 -0.56695863 -0.21836018 -1.09320355 -0.6394564 ]
 [ 0.36533176  0.14872107 -0.8099196   0.15927314  0.51120794]
 [-0.14264175  0.38491974  0.74951029 -0.47730995 -0.05293411]
 [-0.41198439 -0.18253828  0.10500017 -0.15005464 -1.1916487 ]
 [ 1.19560338  0.32949129 -0.89775696  0.46029378  1.48124554]
 [-0.01173483 -0.13814552  0.51479692  0.47014361  1.09978178]
 [ 1.04133848 -1.46328403 -1.14509718  0.70964416  0.62944726]]


Bài 2 – Ma trận không (zero matrix): Ma trận Am×n được gọi là ma trận không khi ai,j = 0, ∀i,j.
Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - A6×7. Gợi ý: sử dụng hàm numpy.zeros((m,n)).
Kết quả xuất ra màn hình.

In [ ]:
o = np.zeros((6, 7))
print(o)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Bài 3 – Ma trận vuông: Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×7 , giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [ ]:
b = np.random.randn(7, 7)
print(b)

[[-0.03640442 -1.26060216 -0.79262249 -1.36030231 -2.96126591  2.06409159
   0.91920197]
 [ 0.65576482  0.27590524 -1.74611127  0.28611568 -0.57176493 -0.2676838
   0.45042516]
 [-0.7708728  -1.29213555  0.2396847  -2.14066783  1.64669207 -1.28020348
   1.46144109]
 [ 0.59821459  1.12404879  0.14415196  0.91431956 -0.39834388 -0.18271622
  -1.49468383]
 [-0.13018349  0.43706195  1.19532038  1.49745233 -0.56113213  0.08851699
  -0.58952057]
 [ 1.08382847  0.1009074   0.20947667  0.9614306   0.50005428  0.25538088
   0.46600007]
 [ 1.24318961  1.33580215  0.29858697  1.39609248  0.00412143 -0.38162626
   0.81609286]]


Bài 4 – Ma trận chéo (diagonal matrix): Ma trận vuông có các phần tử trên đường chéo ai,i ≠ 0
trong khi các phần tử còn lại ai,j = 0, ∀i ≠ j.

In [ ]:
c = np.zeros((6, 6))
np.fill_diagonal(c, 15)
print(c)

[[15.  0.  0.  0.  0.  0.]
 [ 0. 15.  0.  0.  0.  0.]
 [ 0.  0. 15.  0.  0.  0.]
 [ 0.  0.  0. 15.  0.  0.]
 [ 0.  0.  0.  0. 15.  0.]
 [ 0.  0.  0.  0.  0. 15.]]


Bài 5 – Ma trận tam giác trên (upper triangular matrix): Ma trận vuông An×n được gọi là ma
trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường
chéo đều bằng 0.

In [ ]:
d = np.random.randn(8, 8)
tgt = np.triu(d)
print(tgt)

[[-7.46430401e-01 -2.84195605e-01 -4.08601085e-01  2.17029068e+00
   1.28096813e-03 -1.83000426e-01 -2.60359187e-01 -1.21376537e-01]
 [ 0.00000000e+00 -5.86371594e-01  9.89422744e-03  1.90434373e-01
  -5.88172940e-01 -3.27703185e-01 -8.66356650e-01 -7.49122623e-01]
 [ 0.00000000e+00  0.00000000e+00  1.01810445e+00  4.77140823e-01
  -4.34912775e-01  1.27143236e+00  1.18514291e+00  7.34599510e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.93155953e-01
   9.37481461e-01  1.92509028e+00  4.30133889e-01 -1.16818936e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   4.28257454e-01  4.96994795e-01  3.07181921e-01 -1.31661945e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00 -7.16405585e-01  7.47364139e-01 -2.84730862e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  1.74052695e+00 -8.81419227e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   

Bài 6 – Ma trận tam giác dưới (lower triangular matrix): Tương tự bài 5, bạn hãy xây dựng
ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [ ]:
e = np.random.randn(8, 8)
tgd = np.tril(e)
print(tgd)

[[-0.61817503  0.          0.          0.          0.          0.
   0.          0.        ]
 [-0.03228769 -0.27123347  0.          0.          0.          0.
   0.          0.        ]
 [ 1.47834199 -1.63418521 -0.02878229  0.          0.          0.
   0.          0.        ]
 [-0.95343661 -1.35875967  0.56787456 -0.00247459  0.          0.
   0.          0.        ]
 [ 1.6430275   0.1739816  -1.67499445  1.03123018  0.10824136  0.
   0.          0.        ]
 [-0.79887141  0.93429071 -0.8605507  -1.47731906 -0.87088522 -0.05683276
   0.          0.        ]
 [ 0.79008534  0.95600992 -1.35596923  0.37030522  0.81951957  0.45365778
   0.37422328  0.        ]
 [-2.22303502 -1.01865896  0.1910093   0.20627812 -0.62831958 -0.79206135
   0.53915767  0.0998387 ]]


Bài 7 – Ma trận đơn vị (identity matrix): Ma trận đơn vị In có số chiều n là một ma trận vuông
mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận
I9
.

In [ ]:
i = np.identity(9)
print(i)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Bài 8 – Phép toán trên ma trận: sử dụng thư viện NumPy để thực hiện các yêu cầu sau:
1. Phép cộng ma trận: Am×n + Bm×n = Cm×n. Hãy sinh ngẫu nhiên 2 ma trận có kích thước
6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình.
2. Phép nhân vô hướng một số với ma trận: Hãy sinh ngẫu nhiên 1 ma trận có kích thước
5x8. Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này. Kết quả xuất
ra màn hình.
3. Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép
chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.
4. Phép nhân 2 ma trận: Am×n ∙ Bn×p = Cm×p. Hãy sinh ngẫu nhiên 2 ma trận A5×7 và B7×3,
tiến hành nhân 2 ma trận này để thu được ma trận C5×3. Xuất các ma trận trên ra màn hình.
Gợi ý: sử dụng hàm numpy.dot()
 Ma trận khả nghịch: ma trận vuông An×n gọi là khả nghịch (hay không suy biến) nếu tồn
tại một ma trận vuông Bn×n sao cho A ∙ B = In . Khi này, B được gọi là ma trận nghịch
đảo của A và ký hiệu là A
−1
. Cho ma trận A5×7, hãy tính ma trận khả nghịch của A. Gợi

ý: sử dụng hàm numpy.linalg.inv()

In [ ]:
a = np.random.randn(6, 7)
b = np.random.randn(6, 7)
print(a+b)
print()
c = np.random.randn(5, 8)
print(c*3)
print()
d = np.random.randn(3, 7)
print(np.transpose(d))
print()
e = np.random.randn(5, 7)
f = np.random.randn(7, 3)
print(np.dot(e, f))
print()
g = np.random.randn(5, 5)
print(np.linalg.inv(g))

[[-0.82638552  2.37513118 -3.23406234 -0.37178394 -0.02860733 -0.58684214
   3.6607984 ]
 [-1.98189508  0.23129792 -0.47178946 -0.87466607  0.86331091 -1.61627556
   0.64683911]
 [ 0.58066683  0.46115854 -1.43939449 -0.69025406  0.49604664  1.54784385
  -0.5697441 ]
 [ 1.50559438  0.2342317  -1.57645473  0.54560574  0.37235848 -2.81758313
   0.82420476]
 [-0.8845945   0.73122033  1.61694368 -2.59667097  1.39043811 -0.91935756
   0.70834982]
 [ 2.8531165   0.25058181 -0.37765141  0.04176329 -3.82468282  2.25225397
  -1.46295131]]

[[-1.56851519  3.03330889 -1.34319784  1.54006933 -3.84041619 -1.16171185
  -5.94290578 -2.04047511]
 [ 2.50563981  0.96069812 -1.38078747 -1.0476747   2.57012805  2.85559901
   3.67335572  6.4756188 ]
 [-0.0542947  -0.58830045  1.32725808 -2.99571777 -1.06171503 -3.05729432
   0.91756869  0.73411943]
 [ 2.8309834   3.15125057 -1.8173602  -3.51982006 -3.63104052 -1.54013787
   2.3725722   0.1753793 ]
 [ 0.43106841  2.2169759   1.58957762  0.12743959 -1.2156247

Bài 9 – Vector là dạng ma trận đặc biệt: Sử dụng numpy để thực hiện các yêu cầu sau
1. Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. Hãy tạo ngẫu nhiên 1
vector hàng - x có kích thước 1 × 8. Kết quả xuất ra màn hình.
2. Vector cột (column vector) thực chất là ma trận có kích thước m × 1. Hãy tạo ngẫu nhiên
1 vector cột – x có kích thước 8 × 1. Kết quả xuất ra màn hình.

In [ ]:
h = np.random.randn(1, 8)
print(h)
k = np.random.randn(8, 1)
print(k)

[[ 1.50286464 -0.6829318  -0.23760935 -0.77710203 -1.58486305  1.74169206
   1.0169457   0.70324814]]
[[ 0.01803219]
 [ 1.76521169]
 [ 0.32202272]
 [-0.26120902]
 [ 0.67655902]
 [-0.12182515]
 [ 0.78892337]
 [ 1.73270722]]


Bài 10 - Hệ phương trình tuyến tính: Giải hệ phương trình tuyến tính.

In [ ]:
n = int(input("So an cua phuong trinh:"))
A = np.zeros((n, n))
b = []
for i in range(n):
  z = int(input(f"Nhap b[{i+1}]:"))
  b.append(z)
b = np.array(b)
for i in range(0, n):
  for j in range(0, n):
    z = int(input(f"Nhap a[{i+1}, {j+1}]:"))
    A[i][j] = z
A = np.linalg.inv(A)
print(np.dot(A, b))

So an cua phuong trinh:4
Nhap b[1]:10
Nhap b[2]:0
Nhap b[3]:7
Nhap b[4]:2
Nhap a[1, 1]:3
Nhap a[1, 2]:1
Nhap a[1, 3]:-1
Nhap a[1, 4]:1
Nhap a[2, 1]:1
Nhap a[2, 2]:4
Nhap a[2, 3]:1
Nhap a[2, 4]:-10
Nhap a[3, 1]:5
Nhap a[3, 2]:-1
Nhap a[3, 3]:2
Nhap a[3, 4]:6
Nhap a[4, 1]:9
Nhap a[4, 2]:-1
Nhap a[4, 3]:2
Nhap a[4, 4]:6
[-1.25        9.93367347  0.03571429  3.85204082]
