<a href="https://colab.research.google.com/github/TranNhatHan/LamBt/blob/main/BtNumpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cú pháp: numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)

func1d : hàm bạn muốn thực hiện cho từng hàm hay cột

axis : số 0 nếu bạn muốn áp dụng cho từng cột, 1 nếu muốn áp dụng cho từng hàm

arr : ma trận bạn muốn áp dụng thực hiện hàm này

In [ ]:
import numpy as np

Câu 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [ ]:
a = np.random.randint(-20,20, (15, 17))
print(a)

[[  1 -17   1   7   7 -16  14  13  13  12  12  14 -10 -19   6   7   2]
 [ -3   9  18   6   1  17  10   2  -5  14   5   2   3   5  -6  12   8]
 [-17  -5  -5  -2  -7  -3 -16  -9 -15 -12  -1  12   0   4  10   5   1]
 [ 18  16  -4  16  -4   0  -2  -1   6 -12   4 -18 -18  14   6  -1 -14]
 [ 10   6  -3  18 -17   0  -3 -15 -10 -16   3  12 -16   8   8   1 -18]
 [ -7 -16  -3   7  -2  10 -17  17 -15  -4   8   0  15  -8   6  -8 -16]
 [-11   4   9  16 -19  13  10  -4  10  -3   0   4 -17  15  12  -1 -15]
 [-18   2   5  18 -10  -5   9 -11 -10  -4 -17 -18 -18 -10  19   5  -9]
 [-17 -15  13   8  -6 -18  10  13   1  -5  13  10   4  18  -5 -20 -11]
 [ -4 -11   0   5   4  11 -10  19  15   6   7  13  -8   8 -15   0  -3]
 [ 11  17   8 -15  11   8   3  -1 -15  -4   1  -5 -10   0  14  15  19]
 [  5   0   0 -16  -7   8  -8  12  16  -6  -4   6   8  12 -14   2   9]
 [ 16 -12  -9  -2   6  14 -16  17   1  17 -11  -7  -3   1 -17 -14  -2]
 [ 11   2  -3  17  14  -4  -3  -4   7   5 -12 -18  -5 -13  -8  14  15]
 [ 10 

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tim_gia_tri_lon_nhat(vector_a):
  return np.max(vector_a)
np.apply_along_axis(tim_gia_tri_lon_nhat, 1, a)

array([14, 18, 12, 18, 18, 17, 16, 19, 18, 19, 19, 16, 17, 17, 16])

In [ ]:
np.apply_along_axis(tim_gia_tri_lon_nhat, 0, a)

array([18, 17, 18, 18, 14, 17, 14, 19, 16, 17, 13, 14, 16, 18, 19, 15, 19])

Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tim_gia_tri_nho_nhat(vector_a):
  return np.min(vector_a)
np.apply_along_axis(tim_gia_tri_nho_nhat, 1, a)

array([-19,  -6, -17, -18, -18, -17, -19, -18, -20, -15, -15, -16, -17,
       -18, -18])

In [ ]:
np.apply_along_axis(tim_gia_tri_nho_nhat, 0, a)

array([-18, -17,  -9, -16, -19, -18, -17, -15, -15, -16, -17, -18, -18,
       -19, -18, -20, -18])

Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tinh_tong(vector_a):
  return np.sum(vector_a)
np.apply_along_axis(tinh_tong, 1, a)

array([ 47,  98, -60,   6, -32, -33,  23, -72,  -7,  37,  57,  23, -21,
        15, -47])

Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [ ]:
def tinh_tong2(vector_a):
  sum = 0
  for i in vector_a:
    if i//2!=0:
      sum+=i
  return sum
np.apply_along_axis(tinh_tong2, 1, a)

array([ 45,  97, -61,   6, -33, -33,  23, -72,  -8,  37,  56,  23, -23,
        15, -47])

In [ ]:
np.apply_along_axis(tinh_tong2, 0, a)