<a href="https://colab.research.google.com/github/TranNhatHan/LamBt/blob/main/BtNumPy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: Xét không gian R3, một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo giá trị của điểm A nêu trên bằng Numpy.

In [ ]:
import numpy as np
a = np.array([5, 7, 4])
print(a)

Bài 2: Mở rộng không gian lên R15, điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong không gian 15 chiều này bằng Numpy.

In [ ]:
import numpy as np
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Bài 3: Trong không gian Rn, xét vector OA , với O là điểm gốc tọa độ và A là điểm có tọa độ tổng quát là (a1, a2, ..., an). Vector OA lúc này được viết dưới dạng vector cột (column vector) là:

In [ ]:
import numpy as np
n = int(input("Nhap n:"))
c = np.random.randn(n)
print(c)

Nhap n:3
[0.35568806 0.03797436 0.12756991]


Bài 4: Trong không gian R3, xét vector OA. Hãy viết chương trình tính chiều dài của vector OAOA , biết công thức tổng quát để tính chiều dài
vector OA trong không gian Rn là:

In [ ]:
import numpy as np
oa = np.array([7, -5, 8])
dist = np.linalg.norm(oa)
print(dist)

11.74734012447073


Bài 5: Trong không gian Rn
, hãy sinh ngẫu nhiên 2 điểm A và B. Xác định vector ABAB và tính
chiều dài của vector này ‖AB‖. Lưu ý: sử dụng Numpy.

In [ ]:
import numpy as np
n = int(input("Nhap n:"))
a = np.random.randn(n)
b = np.random.randn(n)
dist = np.linalg.norm(a-b)
print(dist)

Nhap n:4
3.763473440194887


Bài 6 - Trong không gian Rn, hãy sinh ngẫu nhiên 2 vector a & b và tính tích vô hướng của 2 vector này.
Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.

In [ ]:
import numpy as np
n = int(input("Nhap n:"))
a = np.random.randn(n)
b = np.random.randn(n)
c = np.inner(a,b)
print(c)

Nhap n:3
2.038046671367756


Bài 7 - Trong không gian Rn, hãy sinh ngẫu nhiên 2 vector a & b và tính tích hữu hướng của 2 vector này.
Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.

In [ ]:
import numpy as np
n = int(input("Nhap n:"))
a = np.random.randn(n)
b = np.random.randn(n)
c = np.cross(a,b)
print(c)

Nhap n:3
[0.90874477 0.00236078 0.14103858]


Bài 8 - Phép chuyển vị (transpose): trong numpy, một vector a khi thực hiện chuyển vị sẽ được
thực hiện thông qua thao tác a.T
Hãy viết chương trình sinh ngẫu nhiên một vector a trong không gian Rn, số nguyên dương n được nhập vào từ bàn phím. Xuất ra màn hình giá của vector a và chuyển vị của vector a

In [ ]:
import numpy as np
n = int(input("Nhap n:"))
a = np.random.randn(n)
b = np.transpose(a)
print(a)
print(b)

Nhap n:3
[ 0.5734961  -0.91941363 -1.38120338]
[ 0.5734961  -0.91941363 -1.38120338]


Bài 9 - Kết hợp cấu trúc list với Numpy: Xét 2 cấu trúc list dưới đây:
a = [1, 2, 3, 4, 5], 
b = [[1], [2], [3], [4], [5]]
Hãy:
1. Xuất a và b ra màn hình
2. Tạo vector tương ứng từ a và b, xuất kết quả ra màn hình
3. Thực hiện phép chuyển vị đối với 2 vector ở trên và xuất kết quả ra màn hình.


In [ ]:
import numpy as np
a = [[1, 2, 3, 4, 5]]
b = [[1], [2], [3], [4], [5]]
print(a)
print(b)
va = np.array(a)
vb = np.array(b)
print(va)
print(vb)
vat = np.transpose(va)
vbt = np.transpose(vb)
print(vat)
print(vbt)

[[1, 2, 3, 4, 5]]
[[1], [2], [3], [4], [5]]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]


Bài 10: Trong không gian Rn, hãy sinh ngẫu nhiên vector a và b⃗ , n là số nguyên dương nhập vào từ bàn phím. Hãy:

1.   Thực hiện phép nhân: ma với m là số bất kỳ, xuất kết quả ra màn hình
2.   Thực hiện phép cộng 2 vector: a + b và xuất kết quả ra màn hình.






In [ ]:
import numpy as np
n = int(input("Nhap n:"))
a = np.random.randn(n)
b = np.random.randn(n)
print(a)
print(b)
print(a*5)
print(a+b)

Nhap n:3
[-0.12020753  0.14406939  0.70321602]
[-1.3734542  -0.24426211 -0.4515574 ]
[-0.60103767  0.72034694  3.5160801 ]
[-1.49366173 -0.10019273  0.25165862]
