<a href="https://colab.research.google.com/github/TranNhatHan/LamBt/blob/main/BtNumPy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

In [ ]:
a = np.arange(7)
b = np.linspace(1.0, 10.0, num=7)
c = np.logspace(2.0, 3.0, num=7)
d = np.random.rand(7)
print(a.T.ndim, a.T.shape, a.ndim, a.shape)
print(b.T.ndim, b.T.shape, b.ndim, b.shape)
print(c.T.ndim, c.T.shape, c.ndim, c.shape)
print(d.T.ndim, d.T.shape, d.ndim, d.shape)

2 (1, 7) 2 (7, 1)
2 (1, 7) 2 (7, 1)
2 (1, 7) 2 (7, 1)
2 (1, 7) 2 (7, 1)


Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận $A_{10x7}$ với giá trị các phần tử của ma trận A
được sinh bởi:
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

In [ ]:
e = np.arange(70).reshape(10, 7)
f = np.linspace(1.0, 10.0, num=70).reshape(10, 7)
g = np.logspace(2.0, 3.0, num=70).reshape(10, 7)
h = np.random.rand(10, 7)
print(e.T.ndim, e.T.shape, e.ndim, e.shape)
print(f.T.ndim, f.T.shape, f.ndim, f.shape)
print(g.T.ndim, g.T.shape, g.ndim, g.shape)
print(h.T.ndim, h.T.shape, h.ndim, h.shape)

2 (7, 10) 2 (10, 7)
2 (7, 10) 2 (10, 7)
2 (7, 10) 2 (10, 7)
2 (7, 10) 2 (10, 7)


Câu 3: Sử dụng thư viện Numpy, hãy:
- Chuyển ma trận A ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())
- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())

In [ ]:
vector = e.flatten()
matrix = vector.reshape(14, 5)
print(vector)
print(matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]]


Câu 4: Sử dụng thư viện Numpy, hãy:
- Tạo ra 1 ma trận $A_{10x15}$ với các giá trị được sinh ra bởi hàm logspace();
- Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);
- Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [ ]:
A = np.logspace(1.0, 3.0, num=150).reshape(10, 15)
print(A[2,:])
print(A[:,4])

[25.27461587 26.06798021 26.88624807 27.73020117 28.60064576 29.4984134
 30.42436177 31.37937544 32.36436676 33.38027674 34.4280759  35.50876522
 36.62337714 37.77297646 38.95866145]
[ 11.31595665  17.99009916  28.60064576  45.46928456  72.28703351
 114.9218701  182.70270042 290.46061216 461.77405711 734.12803971]


Câu 5: Thực hiện các yêu cầu sau:
- Xây dựng hàm tính giá trị trung bình
- Xây dựng hàm tính giá trị trung vị
- Xây dựng hàm tính giá trị yếu vị
- Xây dựng hàm tính phương sai
- Xây dựng hàm tính độ lệch chuẩn
- Hãy tạo ra ma trận $A_{10x15}$ với các giá trị sinh bởi hàm arrange()
- Áp dụng 5 hàm ở trên cho từng hàng của ma trận A
- Áp dụng 5 hàm ở trên cho từng cột của ma trận A

In [ ]:
def mean(A):
  sum = 0
  for i in A:
    sum+=i
  return sum/len(A)

def median(A):
  A.sort()
  n = len(A)
  if n % 2 == 0:
    median1 = A[n//2]
    median2 = A[n//2 - 1]
    median = (median1 + median2)/2
  else:
    median = A[n//2]
  return median

def mode(A):
  A.sort()
  B=[]  
  for i in A:
    B.append(list(A).count(i))
  d = dict(zip(A, B))
  m = [k for (k,v) in d.items() if v == max(B)]
  return m


def variance(A):
  sum = 0
  for i in A:
    sum+=(i-mean(A))**2
  return sum/len(A)

def standard_deviation(A):
  return variance(A)**(1/2)

A = np.arange(150).reshape(10, 15)
print(A)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47  48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104]
 [105 106 107 108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134]
 [135 136 137 138 139 140 141 142 143 144 145 146 147 148 149]]


In [ ]:
print(np.apply_along_axis(mean, 1, A))
print(np.apply_along_axis(mean, 0, A))

[  7.  22.  37.  52.  67.  82.  97. 112. 127. 142.]
[67.5 68.5 69.5 70.5 71.5 72.5 73.5 74.5 75.5 76.5 77.5 78.5 79.5 80.5
 81.5]


In [ ]:
print(np.apply_along_axis(median, 1, A))
print(np.apply_along_axis(median, 0, A))

[  7  22  37  52  67  82  97 112 127 142]
[67.5 68.5 69.5 70.5 71.5 72.5 73.5 74.5 75.5 76.5 77.5 78.5 79.5 80.5
 81.5]


In [ ]:
print(np.apply_along_axis(mode, 1, A))
print(np.apply_along_axis(mode, 0, A))

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47  48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104]
 [105 106 107 108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134]
 [135 136 137 138 139 140 141 142 143 144 145 146 147 148 149]]
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47  48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84  85  86  87 

In [ ]:
print(np.apply_along_axis(variance, 1, A))
print(np.apply_along_axis(variance, 0, A))

[18.66666667 18.66666667 18.66666667 18.66666667 18.66666667 18.66666667
 18.66666667 18.66666667 18.66666667 18.66666667]
[1856.25 1856.25 1856.25 1856.25 1856.25 1856.25 1856.25 1856.25 1856.25
 1856.25 1856.25 1856.25 1856.25 1856.25 1856.25]


In [ ]:
print(np.apply_along_axis(standard_deviation, 1, A))
print(np.apply_along_axis(standard_deviation, 0, A))

[4.3204938 4.3204938 4.3204938 4.3204938 4.3204938 4.3204938 4.3204938
 4.3204938 4.3204938 4.3204938]
[43.08421985 43.08421985 43.08421985 43.08421985 43.08421985 43.08421985
 43.08421985 43.08421985 43.08421985 43.08421985 43.08421985 43.08421985
 43.08421985 43.08421985 43.08421985]
